### PR TITLE
Make sure recording is done in mono.

### PR DESCRIPTION
**Pull request by fabianrost84**
address #22 by explicitly setting the number of recorded channels to 1 (mono)

### CODE REVIEW

**Comment by ildar** [comment]
Why? What is wrong with this patch?

**Comment by fabianrost84** [comment]
Sorry. I merged the patch in my fork of SoundRecorder and deleted the branch. I forgot that it's also needed here.

**Comment by ildar** [comment]
Is @fabianrost84 your fork going to be the new official upstream?

**Comment by fabianrost84** [comment]
Definitely no. I know nearly nothing about programming of Android apps. I just hacked in my needs in my fork. But as @dkim0419 pointed out in #37 there's not much development to be expected here. That's why I forgot about this one. A new official upstream would be great, but that's up to @dkim0419 and the volunteer who would do that I guess.

**Pull request merged**
